name: short_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flexify: ^2.1.1
  flutter_svg: ^2.0.17
  http: ^1.3.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/image 185.png
    - assets/images/splash.jpg
    - assets/images/image 228.png
    - assets/images/image 188.png
    - assets/images/cupcakes.jpg
    - assets/images/hoteats.png
    - assets/images/brownies.jpg
    - assets/images/cake-slices.jpg
    - assets/images/photo-cake.jpg
    - assets/images/fruit-cakes.jpg
    - assets/images/kids-cake.jpg
    - assets/images/IMG_3136 1.png
    - assets/images/image 91.png
    - assets/images/image 84.png
    - assets/images/cake-slice.png
    - assets/images/orie.png
    - assets/images/cnb-stamp 1.png
    - assets/images/Soft Star.svg
    - assets/images/Group 615.svg
    - assets/images/Group 620.svg
    - assets/images/Group 665.svg
    - assets/images/Group 762.svg
    - assets/images/Group 347(1).svg
    - assets/images/Arrow 3.svg
    - assets/images/date-range.svg
    - assets/images/date.svg
    - assets/images/Group 655.svg
    - assets/images/Gmail Logo.png
    - assets/images/Password.png
    - assets/images/cake-image.png
    - assets/images/show.png
    - assets/images/invisible.png
    - assets/images/Floral_Cake.png
    - assets/images/Group 684.svg
    - assets/images/Group 684(1).svg
    - assets/images/Group 351.svg
    - assets/images/check.svg
    - assets/images/Vector.svg
    - assets/images/share.svg
    - assets/images/image.jpg
    - assets/images/image.png
    - assets/images/contact-img1.png
    - assets/images/contact-img2.png
    - assets/images/category.png
    - assets/images/franchises.png
    - assets/images/home.svg
    - assets/images/cake.svg
    - assets/images/store.svg
    - assets/images/basket.svg
    - assets/images/magnifier.svg
    - assets/images/store1.svg
    - assets/images/call.svg
    - assets/images/mail.svg
    - assets/images/facebook.svg
    - assets/images/instagram.svg
    - assets/images/twitter.svg
    - assets/images/whatsapp.svg
    - assets/images/party-popper.svg
    - assets/images/category-cake.png
    - assets/images/category(1).png
    - assets/images/category(2).png
    - assets/images/category(3).png
    - assets/images/category(4).png
    - assets/images/category(5).png
    - assets/images/bg.png
    - assets/images/Vector(1).svg
    - assets/images/Vector(2).svg
    - assets/images/Vector(3).svg
    - assets/images/Frame.svg
    - assets/images/empty-cart.svg
    - assets/images/34.svg
    - assets/images/image 180.jpg
    - assets/images/image 180.png
    - assets/images/image 189.png
    - assets/images/image 190.png
    - assets/images/postal-code.svg
    - assets/images/account 1.svg
    - assets/images/account 2.svg
    - assets/images/user.svg


      # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
